name: Weekly Meal Plan Generation

on:
  schedule:
    # Run at 5:00 AM UTC every Sunday
    - cron: '0 5 * * 0'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  generate-meal-plan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Set up Clasp
        run: |
          echo "${{ secrets.CLASP_TOKEN }}" > ~/.clasprc.json
          
      - name: Push to Google Apps Script
        run: npm run push
        
      - name: Trigger meal plan generation
        run: |
          npm install @google/clasp -g
          clasp run 'manualRun'